
select USER from dual;

CREATE ROLE APP_OWNER;
CREATE ROLE DEVELOPER IDENTIFIED BY blender;
CREATE ROLE TESTER;
CREATE ROLE ANALYST;
CREATE ROLE SERVICE;
CREATE ROLE SECURITY IDENTIFIED BY blender;

DROP ROLE APP_OWNER;
/*
SELECT *
FROM dba_role_privs 
where GRANTED_ROLE IN ('ADMIN', 'APP_OWNER', 'DEVELOPER', 'TESTER', 'ANALYST', 'SERVICE', 'SECURITY');
*/

CREATE USER JARVIS IDENTIFIED BY Blender12345;
CREATE USER HARRY IDENTIFIED BY Blender12345;
CREATE USER PETER IDENTIFIED BY Blender12345;
CREATE USER TOM IDENTIFIED BY Blender12345;
CREATE USER HARVEY IDENTIFIED BY Blender12345;
CREATE USER JESSY IDENTIFIED BY Blender12345;

DROP USER JARVIS;
/*
select * from dba_users where username in ('HARRY', 'JARVIS', 'PETER', 'TOM', 'HARVEY', 'JESSY');
*/


GRANT SELECT ON PAYMENTS TO JARVIS;

GRANT ALL
ON ADMIN.CAR
TO APP_OWNER;

GRANT APP_OWNER TO JARVIS;
REVOKE APP_OWNER FROM JARVIS;


GRANT CONNECT, CREATE SESSION TO JARVIS;

REVOKE CREATE SESSION FROM JARVIS;

GRANT SELECT ON CAR TO JARVIS;
REVOKE SELECT ON CAR FROM JARVIS;

ALTER USER JARVIS DEFAULT ROLE APP_OWNER;
set role APP_OWNER IDENTIFIED BY blender;

SELECT * FROM session_roles;

select ora_database_name from dual;

SELECT * FROM user_role_privs;
SELECT * FROM role_sys_privs;
SELECT * FROM role_tab_privs;

select * from ALL_TABLES where OWNER = 'ADMIN';
select * from DBA_ROLE_PRIVS where grantee = 'ADMIN';